### GET ALL FRIENDS BELONGING TO A USER
GET http://localhost:3001/friends HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpbTIzMjEzIiwiaWQiOjEsImlhdCI6MTc0NDAyNzE3NSwiZXhwIjoxNzQ0MDMwNzc1fQ.5DTmm8viPuB1K9sdRtR3NaiTQQ7ShNAcjVBSLpYAHT8

### SEND FRIEND REQUEST
POST http://localhost:3001/friend-requests/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpbTIzMjEzIiwiaWQiOjEsImlhdCI6MTc0NDAyNzE3NSwiZXhwIjoxNzQ0MDMwNzc1fQ.5DTmm8viPuB1K9sdRtR3NaiTQQ7ShNAcjVBSLpYAHT8

### DELETE FRIEND
DELETE http://localhost:3001/friends/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpbTIzMjEzIiwiaWQiOjEsImlhdCI6MTc0NDAyNzE3NSwiZXhwIjoxNzQ0MDMwNzc1fQ.5DTmm8viPuB1K9sdRtR3NaiTQQ7ShNAcjVBSLpYAHT8