### GET MATCH HISTORIES
GET http://localhost:3001/match-histories

### GET ONE MATCH HISTORY
GET http://localhost:3001/match-histories/1

### CREATE MATCH HISTORY
POST http://localhost:3001/match-histories
Content-Type: application/json

{
    "type": "1v1",
    "tournament_id": null,
    "players": [
        { "player_id": 1, "score": 2, "team": null, "round": null },
        { "player_id": 2, "score": 2, "team": null, "round": null }
    ],
    "winners": [
        { "winner_id": 1}
    ]
}