### GET ALL USERS
GET http://localhost:3001/users HTTP/1.1

### GET USER BY USERNAME
GET http://localhost:3001/users/kmatjuhi HTTP/1.1

### CREATE USER KIM
POST http://localhost:3001/users HTTP/1.1
Content-Type: application/json

{
	"username": "kmatjuhi",
	"email": "kmatjuhi@hive.fr",
	"password": "password"
}

### CREATE USER LUMI
POST http://localhost:3001/users HTTP/1.1
Content-Type: application/json

{
	"username": "lkilpela",
	"email": "lkilpela@hive.fr",
	"password": "password"
}