### GET ALL USERS
GET http://localhost:3001/api/users HTTP/1.1

### GET USER BY ID
GET http://localhost:3001/api/users/1 HTTP/1.1

### CREATE USER KIM
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
	"username": "kmatjuhi",
	"email": "kmatjuhi@hive.fr",
	"password": "password"
}

### CREATE USER LUMI
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
	"username": "lkilpela",
	"email": "lkilpela@hive.fr",
	"password": "password"
}

### UPDATE USER BY ID
PUT http://localhost:3001/api/users/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImttYXRqdWhpIiwiaWQiOjEsImlhdCI6MTc0MzI4MzEyMSwiZXhwIjoxNzQzMjg2NzIxfQ.0FqVzlunBKUrhomSgLU0ONrxDa2cLDxl2XsJRRgk1cs

{
	"email": "newtest@hive.fr"
}