export { ProfilePage } from './ProfilePage'
export { Register } from './Register'
export { Settings } from './Settings'
export { TournamentPage } from './Tournament'
export { Help } from './Help'
export { Dashboard } from './DashBoard'
export { SearchResults } from './SearchResults'
export { LandingPage } from './LandingPage'
